### Send FETCH SONG REQUEST
GET http://localhost:3000/song

### Find SONG REQUEST
GET http://localhost:3000/song/1

### Create New SONG REQUEST
POST http://localhost:3000/song
Content-Type: application/json

{
    "title": "APT",
    "artists": ["Rose", "Bruno Mars"],
    "releaseDate": "2024-10-18",
    "duration": 169
}

### Update SONG REQUEST
PUT http://localhost:3000/song/1

### Delete SONG REQUEST
DELETE http://localhost:3000/song/1
